import { useState } from 'react'
import { Link,useParams } from 'react-router-dom'
import { trails } from '@/data/trails'
import { getPlace,getGuide,getDestinationById } from '@/data'
import { getSavedTrips,getEffectiveItinerary,saveUserItinerary } from '@/lib/storage'
import { appendTrailToDay } from '@/lib/trails'
import { tripPhase } from '@/lib/tripLifecycle'
import { Photo } from '@/components/Photo'
import { StoryCard } from '@/components/StoryCard'
import { RalliiBridge } from '@/components/RalliiBridge'
import { openMap } from '@/lib/links'
export function TrailDetail() {
 const {id}=useParams();const trail=trails.find(t=>t.id===id);const [tripId,setTripId]=useState('');const [day,setDay]=useState(0);const [message,setMessage]=useState('');if(!trail)return <div className="p-6"><h1 className="font-display text-3xl">Trail not found</h1><Link to="/explore?category=Trails">Back to Trails</Link></div>
 const dest=getDestinationById(trail.destinationId)!;const trips=getSavedTrips().filter(t=>t.destinationId===trail.destinationId&&tripPhase(t,getEffectiveItinerary(t.itineraryId))!=='ended');const trip=trips.find(t=>t.id===tripId);const itinerary=trip?getEffectiveItinerary(trip.itineraryId):undefined
 return <article className="mx-auto max-w-3xl px-5 py-6"><p className="eyebrow text-terracotta">Jet Set Trails · {dest.city}</p><h1 className="my-3 font-display text-4xl italic">{trail.title}</h1><p className="text-xs text-ink-soft">{trail.placeIds.length} stops · about {trail.estimatedHours} hours · editorial estimate</p><Photo src={trail.photo} seed={trail.id} alt={dest.city+' · destination context'} className="my-5 h-52 w-full"/><p className="text-sm leading-relaxed text-ink-soft">{trail.description}</p><p className="mt-3 text-xs text-ink-soft">An editorial sequence from existing Jet Set places. Check opening hours and travel between stops.</p><ol className="trail-path my-6 space-y-5">{trail.placeIds.map((pid,i)=>{const p=getPlace(pid)!;return <li key={pid} className="rounded-2xl border border-ink/10 bg-cream p-5"><p className="eyebrow text-terracotta">Stop {i+1} · {p.neighborhood}</p><h2 className="my-2 font-display text-2xl">{p.name}</h2><p className="text-xs uppercase tracking-wider text-ink-soft">{p.isJetSetPick?'Jet Set Pick':'Verified Place'}</p><p className="my-3 text-sm leading-relaxed text-ink-soft">{p.description}</p>{p.mapUrl&&<button className="min-h-11 text-sm text-terracotta" onClick={()=>openMap(p.mapUrl)}>Open map ↗</button>}</li>})}</ol><section className="rounded-2xl bg-cream p-5"><h2 className="font-display text-2xl">Make it part of your trip</h2>{trips.length?<><label className="mt-3 block text-xs">Trip<select aria-label="Trail trip" className="mt-2 block min-h-11 w-full border border-ink/20 p-2" value={tripId} onChange={e=>{setTripId(e.target.value);setDay(0);setMessage('')}}><option value="">Choose a trip</option>{trips.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>{itinerary&&<><label className="mt-3 block text-xs">Day<select aria-label="Trail day" value={day} onChange={e=>setDay(Number(e.target.value))} className="mt-2 block min-h-11 w-full border p-2">{itinerary.days.map((d,i)=><option key={d.day} value={i}>Day {d.day}: {d.theme}</option>)}</select></label><button className="mt-3 min-h-11 text-sm text-terracotta" onClick={()=>{saveUserItinerary(appendTrailToDay(itinerary,trail,day));setMessage('Trail stops added in order. Existing stops kept; duplicates skipped.')}}>Add trail to this day</button></>}<p role="status" className="text-xs text-ink-soft">{message}</p>{message&&<Link className="mt-3 block min-h-11 text-sm text-terracotta" to={'/saved/trips/'+tripId}>Open updated trip →</Link>}</>:<Link className="mt-3 block min-h-11 text-sm text-terracotta" to={'/plan?destination='+dest.id}>Plan a {dest.city} trip →</Link>}</section><div className="mt-6"><RalliiBridge destination={dest}/></div><h2 className="my-5 font-display text-2xl">From the Journal</h2><div className="grid gap-5 sm:grid-cols-2">{trail.relatedGuideIds.slice(0,2).map(gid=>{const g=getGuide(gid);return g?<StoryCard key={gid} guide={g}/>:null})}</div></article>
}
