import { useState,useEffect } from 'react'
import { useParams,Link } from 'react-router-dom'
import { getTrip,getEffectiveItinerary,toggleActivityVisited,saveStoryNote } from '@/lib/storage'
import { getDestinationById,getPlace,getGuidesByDestination,getMediaMomentsByDestination } from '@/data'
import { tripPhase,activityVisitKey,dayNumber } from '@/lib/tripLifecycle'
import { tripStoryStats,makeRecapPng } from '@/lib/tripStory'
import { useTripClock } from '@/lib/useTripClock'
import { Photo } from '@/components/Photo'
import { StoryCard } from '@/components/StoryCard'
import { MediaMomentPlayer } from '@/components/MediaMoment'
function DayNote({tripId,day,note}:{tripId:string;day:number;note:string}){const [text,setText]=useState(note),[saved,setSaved]=useState(false);return <div className="mt-4"><label className="block text-xs text-ink-soft">Your memory of this day<textarea aria-label={'Memory for day '+day} value={text} maxLength={2000} onChange={e=>{setText(e.target.value);setSaved(false)}} className="mt-2 min-h-24 w-full rounded-xl border border-ink/15 bg-parchment p-3 text-sm"/></label><button className="min-h-11 text-xs text-terracotta" onClick={()=>{saveStoryNote(tripId,day,text);setSaved(true)}}>Save memory</button>{saved&&<span role="status" className="ml-3 text-xs">Memory saved.</span>}</div>}
export function TripStory() {
 const {tripId}=useParams();const now=useTripClock();const [image,setImage]=useState(''),[message,setMessage]=useState('');const trip=tripId?getTrip(tripId):undefined;const itinerary=trip?getEffectiveItinerary(trip.itineraryId):undefined;const dest=trip?getDestinationById(trip.destinationId):undefined
 useEffect(()=>()=>{if(image)URL.revokeObjectURL(image)},[image])
 if(!trip||!itinerary||!dest)return <div className="p-6"><h1 className="font-display text-3xl">Story not found</h1><Link to="/saved">Back to Saved</Link></div>
 const stats=tripStoryStats(trip,itinerary),ended=tripPhase(trip,itinerary,now)==='ended';const dateLabel=trip.startDate&&Number.isFinite(dayNumber(trip.startDate))?new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(trip.startDate+'T12:00Z')):'Dates not set';const guides=getGuidesByDestination(dest.id);const photos=[dest.heroPhoto,...guides.flatMap(g=>g.photos?.map(p=>p.src)||[])].filter(Boolean)
 async function exportCard(){try{const blob=await makeRecapPng(dest!.city,stats,dateLabel);const url=URL.createObjectURL(blob);setImage(old=>{if(old)URL.revokeObjectURL(old);return url});const file=new File([blob],'jet-set-trip-story.png',{type:'image/png'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'My Jet Set trip story'});setMessage('Recap shared.')}else{setMessage('Recap ready. Download it below.')}}catch(e){setMessage((e as Error).name==='AbortError'?'Sharing canceled.':(e as Error).message)}}
 return <article className="mx-auto max-w-3xl px-5 py-6"><p className="eyebrow text-terracotta">{ended?'Your trip story':'Your story in progress'}</p><h1 className="my-3 font-display text-4xl italic">{dest.city}</h1><p className="text-sm text-ink-soft">{dateLabel} · {stats.days} days</p><div className="my-5 rounded-2xl bg-cream p-5"><p className="font-display text-2xl">{stats.planned.length} planned places · {stats.neighborhoods.length} neighborhoods</p><p className="mt-2 text-sm text-terracotta">Confirmed places visited: {stats.visited.length}</p><p className="mt-3 text-xs text-ink-soft">Unconfirmed stops remain planned. The photographs and films below are Jet Set archive context, not proof of your visits.</p><button className="mt-3 min-h-11 text-sm text-terracotta" onClick={exportCard}>Create recap image</button><p role="status" className="text-xs text-ink-soft">{message}</p>{image&&<div className="mt-4"><img className="w-full max-w-xs rounded-xl" src={image} alt="Your shareable trip recap with planned and confirmed counts"/><a href={image} download="jet-set-trip-story.png" className="mt-3 inline-block min-h-11 text-sm text-terracotta">Download recap PNG ↓</a></div>}</div>
 {itinerary.days.map((day,i)=>{const dayPlaces=day.activities.map(a=>a.placeId?getPlace(a.placeId):undefined).filter(Boolean);const related=guides.filter(g=>g.placeIds.some(id=>dayPlaces.some(p=>p!.id===id))).slice(0,1);return <section key={day.day} className="my-7"><p className="eyebrow text-terracotta">Day {day.day}</p><h2 className="my-3 font-display text-3xl">{day.theme}</h2><Photo src={dayPlaces.find(p=>p!.photos.length)?.photos[0]||photos[i%photos.length]} seed={'story-'+day.day} alt={dest.city+' · Jet Set archive context'} className="h-52 w-full"/><p className="mt-2 text-xs text-ink-soft">Jet Set archive · destination context</p><div className="mt-4 rounded-2xl bg-cream p-5">{day.activities.map(a=>{const p=a.placeId?getPlace(a.placeId):undefined;const key=activityVisitKey(day.day,a.id),visited=trip.visitedActivityIds?.includes(key);return <div key={a.id} className="border-b border-ink/10 py-3"><p className="text-sm">{p?.name||a.label}</p>{p?<label className="mt-2 flex min-h-11 items-center gap-2 text-xs"><input type="checkbox" checked={visited||false} onChange={()=>toggleActivityVisited(trip.id,key)}/>{visited?'Confirmed visited':'Planned · not confirmed'}</label>:<p className="mt-2 text-xs text-ink-soft">Planned time</p>}</div>})}<DayNote tripId={trip.id} day={day.day} note={trip.storyNotes?.[day.day]||''}/></div>{related.map(g=><div className="mt-4" key={g.id}><StoryCard guide={g}/></div>)}</section>})}
 {getMediaMomentsByDestination(dest.id).length>0&&<section className="my-7"><h2 className="mb-3 font-display text-2xl">From the Jet Set film archive</h2><p className="mb-4 text-xs text-ink-soft">Destination films recorded by Jet Set; these do not document your trip.</p><div className="max-w-md">{getMediaMomentsByDestination(dest.id).slice(0,1).map(m=><MediaMomentPlayer key={m.id} moment={m} className="aspect-[3/4] w-full"/>)}</div></section>}<Link className="min-h-11 text-sm text-terracotta" to={'/saved/trips/'+trip.id}>Back to your itinerary →</Link></article>
}
