import { tripOverlapsCarnival } from '@/lib/carnivalSeason';
import type { Destination,Itinerary } from '@/types'
import { tripExtensions } from '@/lib/constellation'
import { getTripContext } from '@/lib/tripContext'
import { appFamily } from '@/config/appFamily'
import { openExternal } from '@/lib/links'
import { StyleBridge } from './StyleBridge'
import { RalliiBridge } from './RalliiBridge'
export function TripConstellation({destination,tripId,itinerary}:{destination:Destination;tripId:string;itinerary:Itinerary}) {const context=getTripContext(tripId);const extensions=tripExtensions(itinerary);return <section aria-label="Trip constellation" className="my-7 border-t border-ink/15 pt-6"><h2 className="text-center font-display text-3xl italic">Make this trip yours.</h2><div className="mx-auto my-5 max-w-sm rounded-full border border-terracotta/25 bg-cream px-6 py-5 text-center"><p className="eyebrow text-terracotta">Your trip, at the center</p><p className="mt-2 font-display text-2xl">{destination.city}</p><p className="mt-1 text-xs text-ink-soft">{itinerary.days.length} days · {itinerary.answers?.companions||'your travel plans'}</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><StyleBridge destination={destination} context={context} itinerary={itinerary} carnival={tripOverlapsCarnival(destination.id,context?.startDate,itinerary.days.length)}/></div>{extensions.food&&<section className="rounded-2xl border border-ink/10 bg-cream p-5"><p className="eyebrow text-terracotta">Food · Let Them Eat</p><h3 className="my-3 font-display text-2xl">Taste the world.</h3><p className="text-sm leading-relaxed text-ink-soft">Your trip makes room for food. Explore the stories and traditions behind cakes, ramen, cookies and noodles in Let Them Eat.</p><button className="mt-3 min-h-11 text-sm text-terracotta" onClick={()=>openExternal(appFamily['let-them-eat'].iOSURL)}>Explore Let Them Eat →</button></section>}{extensions.family&&<section className="rounded-2xl border border-ink/10 bg-cream p-5"><p className="eyebrow text-terracotta">Family · Little Jetter</p><h3 className="my-3 font-display text-2xl">Bring the little travelers along.</h3><p className="text-sm leading-relaxed text-ink-soft">Prep and packing for traveling with kids. Keep the children’s needs in the plan as your family gets ready.</p>{appFamily['little-jetter'].iOSURL&&<button className="mt-3 min-h-11 text-sm text-terracotta" onClick={()=>openExternal(appFamily['little-jetter'].iOSURL)}>Open Little Jetter →</button>}</section>}{extensions.adventure&&<RalliiBridge destination={destination} itinerary={itinerary}/>}</div></section>}
